version: "3"
services:
  mongodb:
    image: mongo
    container_name: "MongoDBWorkshop"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  mobile-app:

